services:
  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://${dbUser}:${dbPassword}@${dbDomain}/?retryWrites=true&w=majority&appName=${dbCluster}
    env_file:
      - .env  
